// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7aT2oAy2NBryM_GPFtiwV_4IioA1sDEw',
    appId: '1:270029527985:web:253ddb01d87449a2313b90',
    messagingSenderId: '270029527985',
    projectId: 'flutter-firebase-rbac',
    authDomain: 'flutter-firebase-rbac.firebaseapp.com',
    storageBucket: 'flutter-firebase-rbac.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhe-Lj7q1fcgDv28cudSNEwwsFll6_VMY',
    appId: '1:270029527985:android:fb17e471515556bc313b90',
    messagingSenderId: '270029527985',
    projectId: 'flutter-firebase-rbac',
    storageBucket: 'flutter-firebase-rbac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc86tAHioyGYtz_xR2GloWA6WCUT73jNE',
    appId: '1:270029527985:ios:b9bca553e2501308313b90',
    messagingSenderId: '270029527985',
    projectId: 'flutter-firebase-rbac',
    storageBucket: 'flutter-firebase-rbac.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseRbac',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCc86tAHioyGYtz_xR2GloWA6WCUT73jNE',
    appId: '1:270029527985:ios:b9bca553e2501308313b90',
    messagingSenderId: '270029527985',
    projectId: 'flutter-firebase-rbac',
    storageBucket: 'flutter-firebase-rbac.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseRbac',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7aT2oAy2NBryM_GPFtiwV_4IioA1sDEw',
    appId: '1:270029527985:web:390d23a3c1be5fc7313b90',
    messagingSenderId: '270029527985',
    projectId: 'flutter-firebase-rbac',
    authDomain: 'flutter-firebase-rbac.firebaseapp.com',
    storageBucket: 'flutter-firebase-rbac.firebasestorage.app',
  );
}
